# Generated by Django 4.0 on 2021-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('FN', models.CharField(max_length=20)),
                ('MN', models.CharField(max_length=20)),
                ('LN', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('duration', models.CharField(max_length=20)),
                ('status_phd', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('mid', models.IntegerField()),
                ('st_email', models.CharField(max_length=50)),
                ('meet_id', models.IntegerField()),
                ('center_no', models.IntegerField()),
            ],
        ),
    ]
