# Generated by Django 4.0 on 2021-12-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfn', models.CharField(max_length=20)),
                ('mln', models.CharField(max_length=20)),
                ('m_phno', models.CharField(max_length=13)),
                ('m_age', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('m_email', models.CharField(max_length=50)),
            ],
        ),
    ]
