# Generated by Django 4.0 on 2021-12-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='id',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
