# Generated by Django 4.0 on 2021-12-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_mentor_mid_alter_student_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_inst_fn', models.CharField(max_length=20)),
                ('c_inst_ln', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=13)),
                ('sid', models.IntegerField()),
            ],
        ),
    ]
