# Generated by Django 4.0 on 2021-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetings',
            fields=[
                ('FN', models.CharField(max_length=20)),
                ('meet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date1', models.DateField(max_length=20)),
                ('date2', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='thesis',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('FN', models.CharField(max_length=20)),
                ('thesis_submission_status', models.CharField(max_length=20)),
                ('date_of_submission', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='viva',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('FN', models.CharField(max_length=20)),
                ('viva_status', models.CharField(max_length=20)),
                ('pcv_or_cv', models.CharField(max_length=20)),
                ('pcv_status', models.CharField(max_length=13)),
                ('cv_status', models.IntegerField()),
            ],
        ),
    ]
