# Generated by Django 4.0 on 2021-12-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_alter_viva_cv_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='s_id',
            new_name='sid',
        ),
    ]
