# Generated by Django 4.0 on 2021-12-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_rename_s_id_thesis_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuform',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sfn', models.CharField(max_length=20)),
                ('smn', models.CharField(max_length=20)),
                ('sln', models.CharField(max_length=20)),
                ('ph_no', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('dur_phd', models.CharField(max_length=20)),
                ('status_phd', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('m_id', models.IntegerField()),
                ('stu_email', models.CharField(max_length=50)),
                ('meet_id', models.IntegerField()),
                ('center_no', models.IntegerField()),
            ],
        ),
    ]
