# Generated by Django 4.0 on 2021-12-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_stuform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuform',
            name='smn',
        ),
    ]
