# Generated by Django 4.0 on 2021-12-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_remove_stuform_smn'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetform',
            fields=[
                ('FN', models.CharField(max_length=20)),
                ('meet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date1', models.DateField(max_length=20)),
                ('date2', models.DateField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='dur_phd',
            new_name='duration_of_phd',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='m_id',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='meet_id',
            new_name='mentor_id',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='ph_no',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='sfn',
            new_name='status_of_phd',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='stu_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='sln',
            new_name='student_first_name',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='s_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='stuform',
            old_name='status_phd',
            new_name='student_last_name',
        ),
    ]
